= CONTRIBUTING

== Thinking of Contributing

If you're unsure about anything, just ask -- or submit the issue or pull request anyway. The worst that can happen is you'll be politely asked to change something. We love all friendly contributions.

We encourage you to read this project's CONTRIBUTING policy (you are here), its link:LICENSE.adoc[LICENSE], and its link:README.adoc[README].

=== Policies

We want to ensure a welcoming environment for all of our projects. Our contributers follow the [Red Hat's Code of Conduct] and all contributors should do the same.

We adhere to the [Red Hat Open Source Policy].

=== Public domain

This project is in the public domain within the United States, and copyright and related rights in the work worldwide are waived through the [CC0 1.0 Universal public domain dedication](https://creativecommons.org/publicdomain/zero/1.0/).

All contributions to the project are released under CC0 dedication. By submitting a pull request, you agree to comply with this waiver of the copyright interest.

=== CONTRIBUTING Template Inspiration
https://github.com/18F/open-source-policy/blob/master/README_TEMPLATE.md[18F Open Source Policy README Template]
